Add rollback capability

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -100,25 +100,24 @@ test production server:
     - curl http://$PRODUCTION_SERVER:8000 | grep $APP_VERSION
     - |
       if [[ $? -ne 0 ]]; then
-        sed -i "s/$APP_VERSION/$FORMER_IMAGE_VERSION/" docker-compose.yml.example
+        if [ $FORMER_IMAGE_VERSION -eq 0 ]; then
+          echo "Failed and cannot rollback!"
+          exit 1
+        else:
+          sed -i "s/$APP_VERSION/$FORMER_IMAGE_VERSION/" docker-compose.yml.example
+          scp docker-compose.yml.example $PRODUCTION_USER@$PRODUCTION_SERVER:/tmp/docker-compose.yml
+          ssh $PRODUCTION_USER@$PRODUCTION_SERVER "cd /tmp && docker compose pull && docker compose up -d"
+          sleep 10
+          curl http://$PRODUCTION_SERVER:8000 | grep $FORMER_IMAGE_VERSION
+          if [[ $? -ne 0 ]]; then
+            echo "Rollback failed!"
+            exit 1
+          else:
+            echo "Rollback was Successful"
+            exit 0
+          fi
+        fi
       else:
         echo "Success"
         exit 0
-      fi
-    - |
-      if [ $FORMER_IMAGE_VERSION -eq 0 ]; then
-        echo "Failed and cannot rollback!"
-        exit 1
-      else:
-        scp docker-compose.yml.example $PRODUCTION_USER@$PRODUCTION_SERVER:/tmp/docker-compose.yml
-        ssh $PRODUCTION_USER@$PRODUCTION_SERVER "cd /tmp && docker compose pull && docker compose up -d"
-        sleep 10
-        curl http://$PRODUCTION_SERVER:8000 | grep $FORMER_IMAGE_VERSION
-        if [[ $? -ne 0 ]]; then
-          echo "Rollback failed!"
-          exit 1
-        else:
-          echo "Rollback was Successful"
-          exit 0
-        fi
       fi
